dtb-$(CONFIG_ARCH_UNIPHIER) += \
	uniphier-ph1-ld11-ref.dtb \
	uniphier-ph1-ld11-global.dtb \
	uniphier-ph1-ld20-ref.dtb \
	uniphier-ph1-ld20-global.dtb \
	uniphier-ph1-ld20-global16g.dtb \
	uniphier-ph1-ld21-global.dtb

always		:= $(dtb-y)
clean-files	:= *.dtb
