obj-y					+= clk-uniphier-core.o

obj-$(CONFIG_CLK_UNIPHIER_MIO)		+= clk-uniphier-mio.o
#obj-$(CONFIG_CLK_UNIPHIER_PERI)		+= clk-uniphier-peri.o
#obj-$(CONFIG_CLK_UNIPHIER_SLD3)	+= clk-ph1-sld3.o
#obj-$(CONFIG_CLK_UNIPHIER_LD4)		+= clk-ph1-ld4.o
#obj-$(CONFIG_CLK_UNIPHIER_PRO4)	+= clk-ph1-pro4.o
#obj-$(CONFIG_CLK_UNIPHIER_SLD8)	+= clk-ph1-sld8.o
#obj-$(CONFIG_CLK_UNIPHIER_PRO5)	+= clk-ph1-pro5.o
#obj-$(CONFIG_CLK_UNIPHIER_PXS2)	+= clk-proxstream2.o
