
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     mojo/shell/public/interfaces/connector.mojom
//

package org.chromium.mojom.mojo.shell.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;


public interface Connector extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends Connector, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<Connector, Connector.Proxy> MANAGER = Connector_Internal.MANAGER;


    void connect(
Identity target, org.chromium.mojo.bindings.InterfaceRequest<InterfaceProvider> remoteInterfaces, InterfaceProvider localInterfaces, ClientProcessConnection clientProcessConnection, 
ConnectResponse callback);

    interface ConnectResponse extends org.chromium.mojo.bindings.Callbacks.Callback3<Integer, String, Integer> { }



    void clone(
org.chromium.mojo.bindings.InterfaceRequest<Connector> request);


}
