
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     mojo/shell/public/interfaces/connector.mojom
//

package org.chromium.mojom.mojo.shell.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;

public final class ConnectResult {


    public static final int SUCCEEDED = 0;

    public static final int INVALID_ARGUMENT = SUCCEEDED + 1;

    public static final int ACCESS_DENIED = INVALID_ARGUMENT + 1;


    private ConnectResult() {}

}