
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ipc/mojo/ipc.mojom
//

package org.chromium.mojom.IPC.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;


public interface Channel extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends Channel, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<Channel, Channel.Proxy> MANAGER = Channel_Internal.MANAGER;


    void receive(
byte[] data, SerializedHandle[] handles);


}
