
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/WebKit/public/platform/modules/permissions/permission_status.mojom
//

package org.chromium.mojom.blink.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;

public final class PermissionStatus {


    public static final int GRANTED = 0;

    public static final int DENIED = GRANTED + 1;

    public static final int ASK = DENIED + 1;

    public static final int LAST = (int) (PermissionStatus.ASK);


    private PermissionStatus() {}

}