
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     content/common/background_sync_service.mojom
//

package org.chromium.mojom.content.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;


public interface BackgroundSyncServiceClient extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends BackgroundSyncServiceClient, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<BackgroundSyncServiceClient, BackgroundSyncServiceClient.Proxy> MANAGER = BackgroundSyncServiceClient_Internal.MANAGER;


    void sync(
String tag, int lastChance, 
SyncResponse callback);

    interface SyncResponse extends org.chromium.mojo.bindings.Callbacks.Callback1<Integer> { }


}
