
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     content/common/service_worker/embedded_worker_setup.mojom
//

package org.chromium.mojom.content.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;


public interface EmbeddedWorkerSetup extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends EmbeddedWorkerSetup, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<EmbeddedWorkerSetup, EmbeddedWorkerSetup.Proxy> MANAGER = EmbeddedWorkerSetup_Internal.MANAGER;


    void exchangeInterfaceProviders(
int threadId, org.chromium.mojo.bindings.InterfaceRequest<org.chromium.mojom.mojo.shell.mojom.InterfaceProvider> remoteInterfaces, org.chromium.mojom.mojo.shell.mojom.InterfaceProvider localInterfaces);


}
