
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     content/common/presentation/presentation_service.mojom
//

package org.chromium.mojom.content.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;

public final class PresentationConnectionState {


    public static final int CONNECTING = 0;

    public static final int CONNECTED = CONNECTING + 1;

    public static final int CLOSED = CONNECTED + 1;

    public static final int TERMINATED = CLOSED + 1;


    private PresentationConnectionState() {}

}