
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     content/common/presentation/presentation_service.mojom
//

package org.chromium.mojom.content.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;

public final class PresentationMessageType {


    public static final int TEXT = 0;

    public static final int ARRAY_BUFFER = TEXT + 1;

    public static final int BLOB = ARRAY_BUFFER + 1;


    private PresentationMessageType() {}

}