
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     content/common/storage_partition_service.mojom
//

package org.chromium.mojom.content.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;


class StoragePartitionService_Internal {

    public static final org.chromium.mojo.bindings.Interface.Manager<StoragePartitionService, StoragePartitionService.Proxy> MANAGER =
            new org.chromium.mojo.bindings.Interface.Manager<StoragePartitionService, StoragePartitionService.Proxy>() {
    
        public String getName() {
            return "content::mojom::StoragePartitionService";
        }
    
        public int getVersion() {
          return 0;
        }
    
        public Proxy buildProxy(org.chromium.mojo.system.Core core,
                                org.chromium.mojo.bindings.MessageReceiverWithResponder messageReceiver) {
            return new Proxy(core, messageReceiver);
        }
    
        public Stub buildStub(org.chromium.mojo.system.Core core, StoragePartitionService impl) {
            return new Stub(core, impl);
        }
    
        public StoragePartitionService[] buildArray(int size) {
          return new StoragePartitionService[size];
        }
    };


    private static final int OPEN_LOCAL_STORAGE_ORDINAL = 0;


    static final class Proxy extends org.chromium.mojo.bindings.Interface.AbstractProxy implements StoragePartitionService.Proxy {

        Proxy(org.chromium.mojo.system.Core core,
              org.chromium.mojo.bindings.MessageReceiverWithResponder messageReceiver) {
            super(core, messageReceiver);
        }


        @Override
        public void openLocalStorage(
org.chromium.mojom.url.mojom.Origin origin, LevelDbObserver observer, org.chromium.mojo.bindings.InterfaceRequest<LevelDbWrapper> database) {

            StoragePartitionServiceOpenLocalStorageParams _message = new StoragePartitionServiceOpenLocalStorageParams();

            _message.origin = origin;

            _message.observer = observer;

            _message.database = database;


            getProxyHandler().getMessageReceiver().accept(
                    _message.serializeWithHeader(
                            getProxyHandler().getCore(),
                            new org.chromium.mojo.bindings.MessageHeader(OPEN_LOCAL_STORAGE_ORDINAL)));

        }


    }

    static final class Stub extends org.chromium.mojo.bindings.Interface.Stub<StoragePartitionService> {

        Stub(org.chromium.mojo.system.Core core, StoragePartitionService impl) {
            super(core, impl);
        }

        @Override
        public boolean accept(org.chromium.mojo.bindings.Message message) {
            try {
                org.chromium.mojo.bindings.ServiceMessage messageWithHeader =
                        message.asServiceMessage();
                org.chromium.mojo.bindings.MessageHeader header = messageWithHeader.getHeader();
                if (!header.validateHeader(org.chromium.mojo.bindings.MessageHeader.NO_FLAG)) {
                    return false;
                }
                switch(header.getType()) {
            
                    case org.chromium.mojo.bindings.InterfaceControlMessagesConstants.RUN_OR_CLOSE_PIPE_MESSAGE_ID:
                        return org.chromium.mojo.bindings.InterfaceControlMessagesHelper.handleRunOrClosePipe(
                                StoragePartitionService_Internal.MANAGER, messageWithHeader);
            
            
            
            
            
                    case OPEN_LOCAL_STORAGE_ORDINAL: {
            
                        StoragePartitionServiceOpenLocalStorageParams data =
                                StoragePartitionServiceOpenLocalStorageParams.deserialize(messageWithHeader.getPayload());
            
                        getImpl().openLocalStorage(data.origin, data.observer, data.database);
                        return true;
                    }
            
            
                    default:
                        return false;
                }
            } catch (org.chromium.mojo.bindings.DeserializationException e) {
                System.err.println(e.toString());
                return false;
            }
        }

        @Override
        public boolean acceptWithResponder(org.chromium.mojo.bindings.Message message, org.chromium.mojo.bindings.MessageReceiver receiver) {
            try {
                org.chromium.mojo.bindings.ServiceMessage messageWithHeader =
                        message.asServiceMessage();
                org.chromium.mojo.bindings.MessageHeader header = messageWithHeader.getHeader();
                if (!header.validateHeader(org.chromium.mojo.bindings.MessageHeader.MESSAGE_EXPECTS_RESPONSE_FLAG)) {
                    return false;
                }
                switch(header.getType()) {
            
                    case org.chromium.mojo.bindings.InterfaceControlMessagesConstants.RUN_MESSAGE_ID:
                        return org.chromium.mojo.bindings.InterfaceControlMessagesHelper.handleRun(
                                getCore(), StoragePartitionService_Internal.MANAGER, messageWithHeader, receiver);
            
            
            
            
                    default:
                        return false;
                }
            } catch (org.chromium.mojo.bindings.DeserializationException e) {
                System.err.println(e.toString());
                return false;
            }
        }
    }


    
    static final class StoragePartitionServiceOpenLocalStorageParams extends org.chromium.mojo.bindings.Struct {
    
        private static final int STRUCT_SIZE = 32;
        private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY = new org.chromium.mojo.bindings.DataHeader[] {new org.chromium.mojo.bindings.DataHeader(32, 0)};
        private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
    
    
    
    
    
        public org.chromium.mojom.url.mojom.Origin origin;
    
        public LevelDbObserver observer;
    
        public org.chromium.mojo.bindings.InterfaceRequest<LevelDbWrapper> database;
    
    
    
        private StoragePartitionServiceOpenLocalStorageParams(int version) {
            super(STRUCT_SIZE, version);
    
    
    
    
    
    
    
        }
    
        public StoragePartitionServiceOpenLocalStorageParams() {
            this(0);
        }
    
        public static StoragePartitionServiceOpenLocalStorageParams deserialize(org.chromium.mojo.bindings.Message message) {
            return decode(new org.chromium.mojo.bindings.Decoder(message));
        }
    
        @SuppressWarnings("unchecked")
        public static StoragePartitionServiceOpenLocalStorageParams decode(org.chromium.mojo.bindings.Decoder decoder0) {
            if (decoder0 == null) {
                return null;
            }
            org.chromium.mojo.bindings.DataHeader mainDataHeader = decoder0.readAndValidateDataHeader(VERSION_ARRAY);
            StoragePartitionServiceOpenLocalStorageParams result = new StoragePartitionServiceOpenLocalStorageParams(mainDataHeader.elementsOrVersion);
    
    
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(8, false);
                
                result.origin = org.chromium.mojom.url.mojom.Origin.decode(decoder1);
                
                
            }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                
                result.observer = decoder0.readServiceInterface(16, false, LevelDbObserver.MANAGER);
                
            }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                
                result.database = decoder0.readInterfaceRequest(24, false);
                
            }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
            return result;
        }
    
        @SuppressWarnings("unchecked")
        @Override
        protected final void encode(org.chromium.mojo.bindings.Encoder encoder) {
    
            org.chromium.mojo.bindings.Encoder encoder0 = encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);
    
    
    
            
            
            encoder0.encode(origin, 8, false);
            
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
            
            
            encoder0.encode(observer, 16, false, LevelDbObserver.MANAGER);
            
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
            
            
            encoder0.encode(database, 24, false);
            
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
        }
    
        /**
         * @see Object#equals(Object)
         */
        @Override
        public boolean equals(Object object) {
            if (object == this)
                return true;
            if (object == null)
                return false;
            if (getClass() != object.getClass())
                return false;
    
            StoragePartitionServiceOpenLocalStorageParams other = (StoragePartitionServiceOpenLocalStorageParams) object;
    
            if (!org.chromium.mojo.bindings.BindingsHelper.equals(this.origin, other.origin))
                return false;
    
            if (!org.chromium.mojo.bindings.BindingsHelper.equals(this.observer, other.observer))
                return false;
    
            if (!org.chromium.mojo.bindings.BindingsHelper.equals(this.database, other.database))
                return false;
    
    
            return true;
        }
    
        /**
         * @see Object#hashCode()
         */
        @Override
        public int hashCode() {
            final int prime = 31;
            int result = prime + getClass().hashCode();
    
            result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(origin);
    
            result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(observer);
    
            result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(database);
    
            return result;
        }
    }



}
