
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     components/web_cache/public/interfaces/web_cache.mojom
//

package org.chromium.mojom.web_cache.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;


class WebCache_Internal {

    public static final org.chromium.mojo.bindings.Interface.Manager<WebCache, WebCache.Proxy> MANAGER =
            new org.chromium.mojo.bindings.Interface.Manager<WebCache, WebCache.Proxy>() {
    
        public String getName() {
            return "web_cache::mojom::WebCache";
        }
    
        public int getVersion() {
          return 0;
        }
    
        public Proxy buildProxy(org.chromium.mojo.system.Core core,
                                org.chromium.mojo.bindings.MessageReceiverWithResponder messageReceiver) {
            return new Proxy(core, messageReceiver);
        }
    
        public Stub buildStub(org.chromium.mojo.system.Core core, WebCache impl) {
            return new Stub(core, impl);
        }
    
        public WebCache[] buildArray(int size) {
          return new WebCache[size];
        }
    };


    private static final int SET_CACHE_CAPACITIES_ORDINAL = 0;

    private static final int CLEAR_CACHE_ORDINAL = 1;


    static final class Proxy extends org.chromium.mojo.bindings.Interface.AbstractProxy implements WebCache.Proxy {

        Proxy(org.chromium.mojo.system.Core core,
              org.chromium.mojo.bindings.MessageReceiverWithResponder messageReceiver) {
            super(core, messageReceiver);
        }


        @Override
        public void setCacheCapacities(
long minDeadCapacity, long maxDeadCapacity, long capacity) {

            WebCacheSetCacheCapacitiesParams _message = new WebCacheSetCacheCapacitiesParams();

            _message.minDeadCapacity = minDeadCapacity;

            _message.maxDeadCapacity = maxDeadCapacity;

            _message.capacity = capacity;


            getProxyHandler().getMessageReceiver().accept(
                    _message.serializeWithHeader(
                            getProxyHandler().getCore(),
                            new org.chromium.mojo.bindings.MessageHeader(SET_CACHE_CAPACITIES_ORDINAL)));

        }


        @Override
        public void clearCache(
boolean onNavigation) {

            WebCacheClearCacheParams _message = new WebCacheClearCacheParams();

            _message.onNavigation = onNavigation;


            getProxyHandler().getMessageReceiver().accept(
                    _message.serializeWithHeader(
                            getProxyHandler().getCore(),
                            new org.chromium.mojo.bindings.MessageHeader(CLEAR_CACHE_ORDINAL)));

        }


    }

    static final class Stub extends org.chromium.mojo.bindings.Interface.Stub<WebCache> {

        Stub(org.chromium.mojo.system.Core core, WebCache impl) {
            super(core, impl);
        }

        @Override
        public boolean accept(org.chromium.mojo.bindings.Message message) {
            try {
                org.chromium.mojo.bindings.ServiceMessage messageWithHeader =
                        message.asServiceMessage();
                org.chromium.mojo.bindings.MessageHeader header = messageWithHeader.getHeader();
                if (!header.validateHeader(org.chromium.mojo.bindings.MessageHeader.NO_FLAG)) {
                    return false;
                }
                switch(header.getType()) {
            
                    case org.chromium.mojo.bindings.InterfaceControlMessagesConstants.RUN_OR_CLOSE_PIPE_MESSAGE_ID:
                        return org.chromium.mojo.bindings.InterfaceControlMessagesHelper.handleRunOrClosePipe(
                                WebCache_Internal.MANAGER, messageWithHeader);
            
            
            
            
            
                    case SET_CACHE_CAPACITIES_ORDINAL: {
            
                        WebCacheSetCacheCapacitiesParams data =
                                WebCacheSetCacheCapacitiesParams.deserialize(messageWithHeader.getPayload());
            
                        getImpl().setCacheCapacities(data.minDeadCapacity, data.maxDeadCapacity, data.capacity);
                        return true;
                    }
            
            
            
            
            
                    case CLEAR_CACHE_ORDINAL: {
            
                        WebCacheClearCacheParams data =
                                WebCacheClearCacheParams.deserialize(messageWithHeader.getPayload());
            
                        getImpl().clearCache(data.onNavigation);
                        return true;
                    }
            
            
                    default:
                        return false;
                }
            } catch (org.chromium.mojo.bindings.DeserializationException e) {
                System.err.println(e.toString());
                return false;
            }
        }

        @Override
        public boolean acceptWithResponder(org.chromium.mojo.bindings.Message message, org.chromium.mojo.bindings.MessageReceiver receiver) {
            try {
                org.chromium.mojo.bindings.ServiceMessage messageWithHeader =
                        message.asServiceMessage();
                org.chromium.mojo.bindings.MessageHeader header = messageWithHeader.getHeader();
                if (!header.validateHeader(org.chromium.mojo.bindings.MessageHeader.MESSAGE_EXPECTS_RESPONSE_FLAG)) {
                    return false;
                }
                switch(header.getType()) {
            
                    case org.chromium.mojo.bindings.InterfaceControlMessagesConstants.RUN_MESSAGE_ID:
                        return org.chromium.mojo.bindings.InterfaceControlMessagesHelper.handleRun(
                                getCore(), WebCache_Internal.MANAGER, messageWithHeader, receiver);
            
            
            
            
            
            
                    default:
                        return false;
                }
            } catch (org.chromium.mojo.bindings.DeserializationException e) {
                System.err.println(e.toString());
                return false;
            }
        }
    }


    
    static final class WebCacheSetCacheCapacitiesParams extends org.chromium.mojo.bindings.Struct {
    
        private static final int STRUCT_SIZE = 32;
        private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY = new org.chromium.mojo.bindings.DataHeader[] {new org.chromium.mojo.bindings.DataHeader(32, 0)};
        private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
    
    
    
    
    
        public long minDeadCapacity;
    
        public long maxDeadCapacity;
    
        public long capacity;
    
    
    
        private WebCacheSetCacheCapacitiesParams(int version) {
            super(STRUCT_SIZE, version);
    
    
    
    
    
    
    
        }
    
        public WebCacheSetCacheCapacitiesParams() {
            this(0);
        }
    
        public static WebCacheSetCacheCapacitiesParams deserialize(org.chromium.mojo.bindings.Message message) {
            return decode(new org.chromium.mojo.bindings.Decoder(message));
        }
    
        @SuppressWarnings("unchecked")
        public static WebCacheSetCacheCapacitiesParams decode(org.chromium.mojo.bindings.Decoder decoder0) {
            if (decoder0 == null) {
                return null;
            }
            org.chromium.mojo.bindings.DataHeader mainDataHeader = decoder0.readAndValidateDataHeader(VERSION_ARRAY);
            WebCacheSetCacheCapacitiesParams result = new WebCacheSetCacheCapacitiesParams(mainDataHeader.elementsOrVersion);
    
    
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                
                result.minDeadCapacity = decoder0.readLong(8);
                
            }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                
                result.maxDeadCapacity = decoder0.readLong(16);
                
            }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                
                result.capacity = decoder0.readLong(24);
                
            }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
            return result;
        }
    
        @SuppressWarnings("unchecked")
        @Override
        protected final void encode(org.chromium.mojo.bindings.Encoder encoder) {
    
            org.chromium.mojo.bindings.Encoder encoder0 = encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);
    
    
    
            
            
            encoder0.encode(minDeadCapacity, 8);
            
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
            
            
            encoder0.encode(maxDeadCapacity, 16);
            
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
            
            
            encoder0.encode(capacity, 24);
            
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
        }
    
        /**
         * @see Object#equals(Object)
         */
        @Override
        public boolean equals(Object object) {
            if (object == this)
                return true;
            if (object == null)
                return false;
            if (getClass() != object.getClass())
                return false;
    
            WebCacheSetCacheCapacitiesParams other = (WebCacheSetCacheCapacitiesParams) object;
    
            if (this.minDeadCapacity != other.minDeadCapacity)
                return false;
    
            if (this.maxDeadCapacity != other.maxDeadCapacity)
                return false;
    
            if (this.capacity != other.capacity)
                return false;
    
    
            return true;
        }
    
        /**
         * @see Object#hashCode()
         */
        @Override
        public int hashCode() {
            final int prime = 31;
            int result = prime + getClass().hashCode();
    
            result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(minDeadCapacity);
    
            result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(maxDeadCapacity);
    
            result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(capacity);
    
            return result;
        }
    }



    
    static final class WebCacheClearCacheParams extends org.chromium.mojo.bindings.Struct {
    
        private static final int STRUCT_SIZE = 16;
        private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY = new org.chromium.mojo.bindings.DataHeader[] {new org.chromium.mojo.bindings.DataHeader(16, 0)};
        private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
    
    
    
    
    
        public boolean onNavigation;
    
    
    
        private WebCacheClearCacheParams(int version) {
            super(STRUCT_SIZE, version);
    
    
    
        }
    
        public WebCacheClearCacheParams() {
            this(0);
        }
    
        public static WebCacheClearCacheParams deserialize(org.chromium.mojo.bindings.Message message) {
            return decode(new org.chromium.mojo.bindings.Decoder(message));
        }
    
        @SuppressWarnings("unchecked")
        public static WebCacheClearCacheParams decode(org.chromium.mojo.bindings.Decoder decoder0) {
            if (decoder0 == null) {
                return null;
            }
            org.chromium.mojo.bindings.DataHeader mainDataHeader = decoder0.readAndValidateDataHeader(VERSION_ARRAY);
            WebCacheClearCacheParams result = new WebCacheClearCacheParams(mainDataHeader.elementsOrVersion);
    
    
            if (mainDataHeader.elementsOrVersion >= 0) {
                
                
                result.onNavigation = decoder0.readBoolean(8, 0);
                
            }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
            return result;
        }
    
        @SuppressWarnings("unchecked")
        @Override
        protected final void encode(org.chromium.mojo.bindings.Encoder encoder) {
    
            org.chromium.mojo.bindings.Encoder encoder0 = encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);
    
    
    
            
            
            encoder0.encode(onNavigation, 8, 0);
            
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
        }
    
        /**
         * @see Object#equals(Object)
         */
        @Override
        public boolean equals(Object object) {
            if (object == this)
                return true;
            if (object == null)
                return false;
            if (getClass() != object.getClass())
                return false;
    
            WebCacheClearCacheParams other = (WebCacheClearCacheParams) object;
    
            if (this.onNavigation != other.onNavigation)
                return false;
    
    
            return true;
        }
    
        /**
         * @see Object#hashCode()
         */
        @Override
        public int hashCode() {
            final int prime = 31;
            int result = prime + getClass().hashCode();
    
            result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(onNavigation);
    
            return result;
        }
    }



}
