
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     device/serial/data_stream.mojom
//

package org.chromium.mojom.device.serial;

import org.chromium.base.annotations.SuppressFBWarnings;


public interface DataSource extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends DataSource, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<DataSource, DataSource.Proxy> MANAGER = DataSource_Internal.MANAGER;


    void init(
int bufferSize);



    void resume(
);



    void reportBytesReceived(
int bytesSent);


}
