
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     mojo/services/catalog/public/interfaces/resolver.mojom
//

package org.chromium.mojom.catalog.mojom;

import org.chromium.base.annotations.SuppressFBWarnings;


public interface Resolver extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends Resolver, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<Resolver, Resolver.Proxy> MANAGER = Resolver_Internal.MANAGER;


    void resolveInterfaces(
String[] interfaces, 
ResolveInterfacesResponse callback);

    interface ResolveInterfacesResponse extends org.chromium.mojo.bindings.Callbacks.Callback1<String> { }



    void resolveMimeType(
String mimeType, 
ResolveMimeTypeResponse callback);

    interface ResolveMimeTypeResponse extends org.chromium.mojo.bindings.Callbacks.Callback1<String> { }



    void resolveProtocolScheme(
String protocolScheme, 
ResolveProtocolSchemeResponse callback);

    interface ResolveProtocolSchemeResponse extends org.chromium.mojo.bindings.Callbacks.Callback1<String> { }


}
