
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     device/usb/public/interfaces/device.mojom
//

package org.chromium.mojom.device.usb;

import org.chromium.base.annotations.SuppressFBWarnings;

public final class ControlTransferRecipient {


    public static final int DEVICE = 0;

    public static final int INTERFACE = DEVICE + 1;

    public static final int ENDPOINT = INTERFACE + 1;

    public static final int OTHER = ENDPOINT + 1;


    private ControlTransferRecipient() {}

}