
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     device/usb/public/interfaces/device.mojom
//

package org.chromium.mojom.device.usb;

import org.chromium.base.annotations.SuppressFBWarnings;

public final class ControlTransferType {


    public static final int STANDARD = 0;

    public static final int CLASS = STANDARD + 1;

    public static final int VENDOR = CLASS + 1;

    public static final int RESERVED = VENDOR + 1;


    private ControlTransferType() {}

}