
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     device/usb/public/interfaces/device.mojom
//

package org.chromium.mojom.device.usb;

import org.chromium.base.annotations.SuppressFBWarnings;

public final class TransferStatus {


    public static final int COMPLETED = 0;

    public static final int TRANSFER_ERROR = COMPLETED + 1;

    public static final int PERMISSION_DENIED = TRANSFER_ERROR + 1;

    public static final int TIMEOUT = PERMISSION_DENIED + 1;

    public static final int CANCELLED = TIMEOUT + 1;

    public static final int STALLED = CANCELLED + 1;

    public static final int DISCONNECT = STALLED + 1;

    public static final int BABBLE = DISCONNECT + 1;

    public static final int SHORT_PACKET = BABBLE + 1;


    private TransferStatus() {}

}